server:
  port: 8080
  forward-headers-strategy: native
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      protocol-header-https-value: https
      host-header: x-forwarded-host
      port-header: x-forwarded-port

spring:
  application:
    name: buerokratt
  datasource:
    url: jdbc:postgresql://localhost:5432/saml_demo
    username: saml
    password: saml
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/seed.sql

  security:
    saml2:
      relyingparty:
        registration:
          entra:
            assertion-consumer-service:
              location: "https://eastbound-christine-overhurried.ngrok-free.dev/login/saml2/sso/entra"

logging:
  level:
    org.springframework.security.saml2: DEBUG
    org.springframework.security.web: DEBUG
